name: CI

on: push

jobs:
  test:
    name: Lint and Run
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --progress-bar off -r requirements.txt
        pip install --progress-bar off pylint mypy

    - name: Lint
      run: pylint french_fries/* submarine/* screen_app/*

    - name: Typecheck
      run: mypy french_fries/ submarine/ screen_app/

    - name: Run french_fries
      run: ./french_fries/french_fries.py

    - name: Run submarine
      run: ./submarine/main.py

    - name: Run screen_app
      run: ./screen_app/screen_app.py
